# Generated by Django 5.1.7 on 2025-05-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_remove_auction_rating_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="rating",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
