# Generated by Django 5.1.7 on 2025-05-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_auction_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="rating",
        ),
    ]
